### ISSUE TITLE
Out of memory when compressing large dataset

### ISSUE THREAD

**Issue by hieunq95** [j-towns/craystack#19]
Hi, I'm trying to compress a customized dataset that has the size (1000, 1, 128, 128, 128), in which 1000 is the size of the dataset. Each sample in the dataset has the size (128, 128, 128) with dtype=np.uint8, which actually is a [voxelized point cloud](https://www.open3d.org/docs/latest/tutorial/Advanced/voxelization.html). 

I tried the VAE multiset codec in `examples/binary_mnist_vae_multiset.py` for compressing my dataset. It works well when I compress a subset of the dataset with shape (400, 1, 128, 128, 128). When I try to increase the subset size to (600, 1, 128, 128, 128), the `vae_append` function can compress the set, but the `vae_pop` function in the line 

`message, multiset_decoded = vae_pop(message, multiset_size=num_batches)` 

stops working and fails to decode the compressed data. In this case, `num_batches=600` as I'm trying to compress the set (600, 1, 128, 128, 128). I notice that the reason is most likely out of memory (my terminal just outputs `zsh: killed     python ...`). Is there any way to fix the out-of-memory issue for the `vae_pop` decoder? 

I checked the paper [Compressing Multisets with Large Alphabets using Bits-Back Coding](https://arxiv.org/pdf/2107.09202) and found that the limit in the alphabet size is around 2^16 (in Fig. 2), which in my case is 128^3 = 2^21. Maybe it is too large for the Multiset codec, but I was just wondering if there are any ways to work around this issue. Will appreciate any suggestions. 

Regards,
Hieu.

**Comment by dsevero** [comment]
Hi @hieunq95, I'm glad to hear you're using these tools :)

> I checked the paper [Compressing Multisets with Large Alphabets using Bits-Back Coding](https://arxiv.org/pdf/2107.09202) and found that the limit in the alphabet size is around 2^16 (in Fig. 2), which in my case is 128^3 = 2^21.

Actually, that figure is only relevant in the context of the synthetic multisets experiment that starts on page 19. It doesn't mean the multiset codec can't handle alphabet sizes above `2^16`. Your alphabet, from the point of view of the multiset codec, is "the universe of candidates that could end up in the set", which for you I believe is of size `128^3 * 256 = 2^(29)`. This is independent of the batch size (which is the multiset size), so it is true for `num_batches=400` which you mentioned worked fine.

>  I notice that the reason is most likely out of memory (my terminal just outputs zsh: killed     python ...).

Given that both encode and decode work for `num_batches=400`, and encode doesn't throw an out-of-memory error for `num_batches=600`, it could be that you ran out of memory. However, your array in memory uses 1 byte per element and has 600*128^3 elements, which totals around 1.25 GB of space; which isn't anything absurd.

The only meaningful memory overhead in the multiset algorithm is the instantiation of objects from the [`ArraySymbol`](url) class on line 4, one for each element in the batch, but the multiset size is quite small (600) so I would guess this isn't an issue.

To debug, I would suggest compressing your data as a sequence, instead of a set, following the [binary vae example](https://github.com/j-towns/craystack/blob/master/examples/binary_mnist_vae.py). If this doesn't throw an out of memory error, then there might be an issue with the multiset codec which we can investigate. If it does throw an error, then probably the multiset codec isn't introducing that much overhead. You'll just have to somehow release some more RAM in other parts of your code to be able to compress your dataset.

**Comment by hieunq95** [comment]
Hi @dsevero, thank you so much for your suggestion. Yes, you're right, the issue is not out of memory caused by the codec.

I tried to run the code several times and monitored the memory usage at the same time, with both examples of multiset and normal codecs. I found that besides the memory for the codec, I also used a large portion of memory to store the VAE model and the raw data for compression. By splitting the data into a large number of batches (i.e., the `num_batches` variable increases in this line of the [binary MNIST VAE example](https://github.com/j-towns/craystack/blob/992e14d1ecedb1de56eba041bc2d7b72d1084ef3/examples/binary_mnist_vae.py#L51)), the memory runs out quickly. 

> If this doesn't throw an out of memory error, then there might be an issue with the multiset codec which we can investigate.

I don't think there is an issue with the multiset codec. I just found that it consumes more memory than the normal VAE codec, in return for a higher compression rate, which makes sense.

My temporary solution is adding the python `del` keyword with [garbage collection](https://www.geeksforgeeks.org/garbage-collection-python/) right after executing the `vae_append` and `vae_pop` functions to remove unused objects from the memory. Now I can compress my entire dataset with no issue. 

Many thanks for your help!
